apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: devops-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/GruiaIP/DevOpsApp.git
    targetRevision: main
    path: Ex4_NodeWebsite/helm

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: devops

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=false