apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: node-app-ingress
  namespace: devops

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production

spec:
  ingressClassName: traefik

  tls:
    - hosts:
        - ipg-devops.online
        - www.ipg-devops.online
      secretName: ipg-devops-tls

  rules:
    - host: ipg-devops.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: node-service
                port:
                  number: 3000

    - host: www.ipg-devops.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: node-service
                port:
                  number: 3000