apiVersion: v1
kind: ConfigMap
metadata:
  name: node-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}

data:
  APP_NAME: {{ .Values.config.appName | quote }}
  NODE_ENV: {{ .Values.nodeApp.environment.nodeEnv | quote }}
  PROMETHEUS_URL: {{ .Values.nodeApp.environment.prometheusUrl | quote }}